name: Terraform Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:

    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS__FOR_GKE }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS__FOR_GKE }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Get Cluster Credentials
        run: |
          gcloud container clusters get-credentials vibs-gke-cluster \
          --region us-east4 \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify Cluster
        run: kubectl get nodes

      - name: Deploy Kubernetes Resources
        run: kubectl apply -f yaml_files/

      - name: Verify Pods
        run: kubectl get pods

      - name: Verify Services
        run: kubectl get svc